### index
GET https://localhost:8080/api/index

### users
POST https://localhost:8080/api/users
Content-Type: application/json
Authentication: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.Mg.ya8OU8cSS9oSB9x4JVUDoTqGC6F8HYbruK5rq8wmMAY

{
    "page":1,
    "num":10
}

### register
POST https://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name":"zxk7517",
    "email":"zxk7517@qq.com",
    "password":"111111"
}

### login
POST https://localhost:8080/api/auth/login
Content-Type: application/json

{
    "email":"zxk7517@qq.com",
    "password":"111111"
}